apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-learning
  targetNamespace: default
